# starts keycloak and postgres in docker containers
# exposures to the host machine:
# - postgres port 3002
# - keycloak port 3001

version: "3.9"

networks:
  textventure:

volumes:
  postgres:

services:
  postgres:
    image: postgres:14.1
    networks:
      - textventure
    ports:
      - 3002:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  keycloak:
    image: jboss/keycloak:16.1.1
    networks:
      - textventure
    ports:
      - 3001:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=adminSecPw1234
      - DB_VENDOR=postgres
      - DB_ADDR=postgres
      - DB_PORT=3002
      - DB_USER=postgres
      - DB_PASSWORD=postgres
